const styles = {
    paragraph: {
        fontFamily: '-apple-system, BlinkMacSystemFont, sans-serif',
        fontSize: 20,
        color: '#000000',
    },
    input: {
        borderRadius: 8,
        overflow: 'hidden',
        border: 'none',
        padding: 12,
        fontFamily: '-apple-system, BlinkMacSystemFont, sans-serif',
        color: '#f9f9f9',
        backgroundColor: '#000000',
        textAlign: 'center',
        fontWeight: 500,
        fontSize: 18,
    },
    codeBlock: {
        borderRadius: 8,
        overflow: 'hidden',
        padding: 12,
        fontFamily: '-apple-system, BlinkMacSystemFont, sans-serif',
        color: '#fff',
        textAlign: 'center',
        fontWeight: 500,
        fontSize: window.innerWidth > 450 ? 12 : 10,
        backgroundColor: '#000000',
        marginTop: 20,
        marginBottom: 20,
    },
    itemContainer: {
        backgroundImage: 'linear-gradient(90deg, #0064f2 0%, #7400c5 100%)',
        padding: '21px 30px',
        borderRadius: 8,
        marginTop: 26,
    },
    itemHeader: {
        fontFamily: '-apple-system, BlinkMacSystemFont, sans-serif',
        fontWeight: 700,
        fontSize: 26,
        color: '#BDCDD6',
    },
    itemBubble: {
        backgroundColor: '#aaffaa',
        color: '#050505',
        padding: 8,
        margin: 6,
        borderRadius: 8,
        fontFamily: '-apple-system, BlinkMacSystemFont, sans-serif',
        fontSize: 12,
        fontWeight: 500,
        display: 'inline-block',
    },
    itemParagraph: {
        fontFamily: '-apple-system, BlinkMacSystemFont, sans-serif',
        fontSize: 16,
        color: '#BDCDD6',
    },
    spanAnchor: {
        textDecoration: 'none',
    },
    anchorContainer: {
        marginTop: 20,
        marginBottom: 20,
    },
    span: {
        backgroundColor: '#ff0074',
        color: '#fff',
        fontFamily: '-apple-system, BlinkMacSystemFont, sans-serif',
        fontWeight: 500,
        fontSize: 18,
        padding: '21px 30px',
        borderRadius: 8,
    },
    icon: {
        marginRight: 10,
    },
    colorBlock: {
        display: 'inline-block',
        height: 50,
        width: 50,
        margin: 10,
        borderRadius: 8,
        cursor: 'pointer',
    },
    colorRoll: {
        paddingTop: 16,
        paddingBottom: 16,
        paddingLeft: 70,
        paddingRight: 70,
        fontFamily: '-apple-system, BlinkMacSystemFont, sans-serif',
        fontWeight: 500,
        color: '#fff',
        borderRadius: 8,
        marginTop: 16,
    },
    betButton: {
        width: 202,
        padding: 16,
        borderRadius: 8,
        backgroundColor: '#000000',
        fontFamily: '-apple-system, BlinkMacSystemFont, sans-serif',
        fontWeight: 500,
        fontSize: 16,
        color: '#fff',
        marginBottom: 20,
        cursor: 'pointer',
        outline: 'none',
        border: 'none',
    },
    algoSelect: {
        border: '2px solid #16003B',
        fontFamily: '-apple-system, BlinkMacSystemFont, sans-serif',
        color: '#16003B',
        fontWeight: 500,
        borderRadius: 8,
        appearance: 'none',
        backgroundColor: 'transparent',
        paddingLeft: 6,
        paddingRight: 6,
        paddingTop: 10,
        paddingBottom: 8,
        textAlign: 'center',
        margin: 0,
        cursor: 'pointer',
        lineHeight: 'inherit',
    },
    colorCell: {
        display: 'inline-block',
        height: 20,
        width: 20,
        borderRadius: 4,
        margin: 2,
    },
};

export default styles;